apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: solairerove-greeting
  name: solairerove-greeting
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: solairerove-greeting
  type: NodePort
status:
  loadBalancer: {}
