version: "3.4"

services:

  config-server:
    restart: on-failure
    build: ./config-server
    container_name: solairerove-config-server
    image: solairerove/config-server:0.0.1
    entrypoint: java -jar /config-server.jar
    ports:
      - "8001:8001"
    networks:
      - wizarnet

  eureka-server:
    depends_on:
      - config-server
    restart: on-failure
    build: ./eureka-server
    container_name: solairerove-eureka-server
    image: solairerove/eureka-server:0.0.1
    entrypoint: java -jar /eureka-server.jar
    ports:
      - "8761:8761"
    networks:
      - wizarnet

  greeting:
    depends_on:
      - eureka-server
    restart: always
    build: ./greeting
    container_name: solairerove-greeting
    image: solairerove/greeting:0.0.1
    entrypoint: java -jar /greeting.jar
    ports:
      - "8002:8002"
    networks:
      - wizarnet

networks:
  wizarnet:
    driver: bridge
