version: "3.3"

services:

  rabbitmq:
    container_name: rabbit-cloud-bus
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=config-server
      - RABBITMQ_DEFAULT_PASS=config-server

  config-server:
    depends_on:
      - rabbitmq
    restart: on-failure
    build: ./config-server
    container_name: solairerove-config-server
    image: solairerove/config-server:0.0.1
    entrypoint: java -jar /config-server.jar
    ports:
      - "8001:8001"
    networks:
      - wizarnet

  eureka-server:
    depends_on:
      - config-server
    restart: on-failure
    build: ./eureka-server
    container_name: solairerove-eureka-server
    image: solairerove/eureka-server:0.0.1
    entrypoint: java -jar /eureka-server.jar
    ports:
      - "8761:8761"
    networks:
      - wizarnet

  task:
    depends_on:
      - eureka-server
    restart: always
    build: ./task
    container_name: solairerove-task
    image: solairerove/task:0.0.1
    entrypoint: java -jar /task.jar
    ports:
      - "8003:8003"
    networks:
      - wizarnet

  greeting:
    depends_on:
      - task
    restart: always
    build: ./greeting
    container_name: solairerove-greeting
    image: solairerove/greeting:0.0.1
    entrypoint: java -jar /greeting.jar
    ports:
      - "8002:8002"
    networks:
      - wizarnet

networks:
  wizarnet:
    driver: bridge
