spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/solairerove/happy-wizard
          search-paths: configs/eureka-server,configs/greeting

server:
  port: 8001
