spring:
  rabbitmq:
    username: config-server
    password: config-server
    host: localhost
    port: 5672
  cloud:
    config:
      server:
        git:
          uri: https://github.com/solairerove/happy-wizard
          search-paths: configs/eureka-server,configs/greeting

server:
  port: 8001

management:
  security:
    enabled: false